# Generated by Django 4.1 on 2022-10-27 21:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artiste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('age', models.IntegerField(default='')),
            ],
            options={
                'ordering': ('first_name', 'last_name', 'age'),
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('title', models.CharField(default='', max_length=255)),
                ('date_released', models.DateField(default=datetime.datetime.now)),
                ('likes', models.IntegerField(default=0)),
                ('id_artiste', models.CharField(default='', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('artiste', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='musicapp.artiste')),
            ],
            options={
                'ordering': ('title', 'artiste', 'date_released', 'likes', 'id_artiste'),
            },
        ),
        migrations.CreateModel(
            name='Lyric',
            fields=[
                ('content', models.TextField(default='')),
                ('id_song', models.CharField(default='', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('song', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='musicapp.song')),
            ],
            options={
                'ordering': ('song', 'content', 'id_song'),
            },
        ),
    ]
